"""refactor_to_multi_product_architecture

Revision ID: 871657416437
Revises: 
Create Date: 2025-09-28 08:32:41.139248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871657416437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('max_leads_per_month', sa.Integer(), nullable=True),
    sa.Column('max_emails_per_day', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('audience_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('estimated_size', sa.Integer(), nullable=True),
    sa.Column('actual_size', sa.Integer(), nullable=True),
    sa.Column('avg_conversion_rate', sa.Float(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_segments_id'), 'audience_segments', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('primary_audience', sa.String(length=100), nullable=True),
    sa.Column('audience_size_estimate', sa.String(length=50), nullable=True),
    sa.Column('pricing_model', sa.String(length=50), nullable=True),
    sa.Column('starting_price', sa.Float(), nullable=True),
    sa.Column('price_range', sa.String(length=100), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('key_features', sa.JSON(), nullable=True),
    sa.Column('pain_points_solved', sa.JSON(), nullable=True),
    sa.Column('competitor_alternatives', sa.JSON(), nullable=True),
    sa.Column('brand_voice', sa.String(length=100), nullable=True),
    sa.Column('brand_colors', sa.JSON(), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('elevator_pitch', sa.Text(), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('trial_url', sa.String(length=500), nullable=True),
    sa.Column('pricing_url', sa.String(length=500), nullable=True),
    sa.Column('contact_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('monthly_revenue', sa.Float(), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('marketing_priority', sa.String(length=50), nullable=True),
    sa.Column('auto_campaigns_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.Column('audience_filters', sa.JSON(), nullable=True),
    sa.Column('geographic_targeting', sa.JSON(), nullable=True),
    sa.Column('messaging_angle', sa.String(length=100), nullable=True),
    sa.Column('content_themes', sa.JSON(), nullable=True),
    sa.Column('call_to_action', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('automation_enabled', sa.Boolean(), nullable=True),
    sa.Column('primary_goal', sa.String(length=100), nullable=True),
    sa.Column('target_leads', sa.Integer(), nullable=True),
    sa.Column('target_conversions', sa.Integer(), nullable=True),
    sa.Column('budget_allocated', sa.Float(), nullable=True),
    sa.Column('leads_generated', sa.Integer(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('emails_opened', sa.Integer(), nullable=True),
    sa.Column('emails_clicked', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue_generated', sa.Float(), nullable=True),
    sa.Column('cost_per_lead', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('email_frequency', sa.String(length=50), nullable=True),
    sa.Column('max_emails_per_lead', sa.Integer(), nullable=True),
    sa.Column('follow_up_delay_days', sa.Integer(), nullable=True),
    sa.Column('ab_testing_enabled', sa.Boolean(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('secondary_product_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.Column('content_angle', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('content_pillar', sa.String(length=100), nullable=True),
    sa.Column('content_goal', sa.String(length=100), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('target_keywords', sa.String(length=500), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('unique_visitors', sa.Integer(), nullable=True),
    sa.Column('avg_time_on_page', sa.Float(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('leads_generated', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('cta_text', sa.String(length=255), nullable=True),
    sa.Column('cta_clicks', sa.Integer(), nullable=True),
    sa.Column('cta_conversion_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['secondary_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=True)
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=True),
    sa.Column('subject_line', sa.String(length=500), nullable=False),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('personalization_fields', sa.JSON(), nullable=True),
    sa.Column('merge_tags', sa.JSON(), nullable=True),
    sa.Column('target_audiences', sa.JSON(), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('avg_open_rate', sa.Float(), nullable=True),
    sa.Column('avg_click_rate', sa.Float(), nullable=True),
    sa.Column('avg_response_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('customer_type', sa.String(length=100), nullable=True),
    sa.Column('business_size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('qualification_level', sa.String(length=50), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('customer_context', sa.JSON(), nullable=True),
    sa.Column('current_solution', sa.String(length=255), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('decision_timeline', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('conversion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifetime_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('outreach_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('email_template_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('email_type', sa.String(length=50), nullable=True),
    sa.Column('sequence_step', sa.Integer(), nullable=True),
    sa.Column('email_provider', sa.String(length=100), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('opens', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('reply_received', sa.Boolean(), nullable=True),
    sa.Column('unsubscribed', sa.Boolean(), nullable=True),
    sa.Column('variant', sa.String(length=50), nullable=True),
    sa.Column('subject_line_variant', sa.String(length=50), nullable=True),
    sa.Column('open_rate', sa.Float(), nullable=True),
    sa.Column('click_rate', sa.Float(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('follow_up_scheduled', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_log_id'), 'outreach_log', ['id'], unique=False)
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.String(length=500), nullable=False),
    sa.Column('page_title', sa.String(length=500), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('page_category', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('is_pricing_page', sa.Boolean(), nullable=True),
    sa.Column('is_signup_page', sa.Boolean(), nullable=True),
    sa.Column('is_demo_page', sa.Boolean(), nullable=True),
    sa.Column('is_contact_page', sa.Boolean(), nullable=True),
    sa.Column('is_trial_page', sa.Boolean(), nullable=True),
    sa.Column('time_on_page', sa.Integer(), nullable=True),
    sa.Column('scroll_percentage', sa.Float(), nullable=True),
    sa.Column('clicks_on_page', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('is_return_visitor', sa.Boolean(), nullable=True),
    sa.Column('visit_number', sa.Integer(), nullable=True),
    sa.Column('pages_in_session', sa.Integer(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('converted_on_visit', sa.Boolean(), nullable=True),
    sa.Column('conversion_type', sa.String(length=50), nullable=True),
    sa.Column('conversion_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_views_id'), 'page_views', ['id'], unique=False)
    op.create_index(op.f('ix_page_views_session_id'), 'page_views', ['session_id'], unique=False)
    op.create_table('social_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('platform_url', sa.String(length=500), nullable=True),
    sa.Column('hashtags', sa.String(length=500), nullable=True),
    sa.Column('mentions', sa.String(length=500), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('engagement_likes', sa.Integer(), nullable=True),
    sa.Column('engagement_shares', sa.Integer(), nullable=True),
    sa.Column('engagement_comments', sa.Integer(), nullable=True),
    sa.Column('engagement_clicks', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('click_through_rate', sa.Float(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.String(length=50), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('website_clicks', sa.Integer(), nullable=True),
    sa.Column('leads_generated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_log_id'), 'social_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_log_id'), table_name='social_log')
    op.drop_table('social_log')
    op.drop_index(op.f('ix_page_views_session_id'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_id'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_index(op.f('ix_outreach_log_id'), table_name='outreach_log')
    op.drop_table('outreach_log')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_audience_segments_id'), table_name='audience_segments')
    op.drop_table('audience_segments')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###